<a href="https://colab.research.google.com/github/roberto-dionisio/introPyTorch/blob/main/intro_to_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Machine Learning
Goal: learn the basics of Pytorch in order to get familiar with ML concepts, and apply the latter to LatticeGaugeTheories

In [ ]:
# prompt: ---> 2 nvidia-smi
# NameError: name 'nvidia' is not defin
import cuda
import torch
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Tensors
- aka multidimensional array, very simil;ar to Numpy arrays but they work better on gpus
- defaul data type of float32
- obv more suitable for ML/DL stuff

In [21]:
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

CUDA available: True
GPU name: Tesla T4


In [14]:
nparr = np.random.rand(3,2)
torch_arr = torch.tensor(nparr)
#nparr, nparr.dtype #numpy defaul dtype is float64, converting a np array to a torch tensor inherit np dtype
torch_arr, torch_arr.dtype

(tensor([[0.6742, 0.4470],
         [0.2318, 0.1261],
         [0.6300, 0.0472]], dtype=torch.float64),
 torch.float64)

In [18]:
torch_arr2 = torch.rand(3,2)
torch_arr2, torch_arr2.dtype #torch defaul dtype is float32

(tensor([[0.1091, 0.9588],
         [0.1033, 0.4618],
         [0.7838, 0.1156]]),
 torch.float32)

In [19]:
torch_arr2 = torch.rand(3,2, dtype=torch.float64) #forced to be float64
torch_arr2, torch_arr2.dtype

(tensor([[0.1596, 0.9848],
         [0.1739, 0.0775],
         [0.3940, 0.0749]], dtype=torch.float64),
 torch.float64)

In [27]:
my_torch = torch.arange(1,10)
my_torch = my_torch.reshape(3,3) #check differences between torch.reshape() and torch.view()
my_torch, my_torch.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))